### ISSUE TITLE
[1.18.1] Suggestion to disable throwing the selected item while in inventories

### ISSUE THREAD

**Issue by Raidobw2** [alRex-U/Throwability#5]
Hello, I would to suggest to disable item throw while in an inventory or a chest for example. For example people might rebind the key to 'R' or another one since it's close to WASD keys for movement. 'R' is usually bound to checking recipes with JEI or REI. This would also make the mod more compatible with JEI or REI, allowing you to throw items with 'R' while walking around, but also to check recipes when you need to craft and have the inventory open. Currently it's bound to 'U', and usually in JEI/REI it stands for checking the uses, so the same thing applies to that too. Thanks!
![throw_in_inventory](https://user-images.githubusercontent.com/17010632/155283067-432612af-aed9-43b6-840d-8d10ff603bc0.gif)

**Comment by alRex-U** [comment]
Yes, this is clearly a bug. I want to fix it.
Thank-you for reporting!

**Comment by alRex-U** [comment]
I fixed this issue.
If this reproduced again, please report.

**Comment by Raidobw2** [comment]
It works perfectly now, and I can even see recipes in the inventory as well when throwing is bound to 'R'. Thank you very much!

**Comment by alRex-U** [comment]
No problem, thank-you for reporting!
